# วิธีการสร้าง Torch tensor เเบบต่าง ๆ

In [ ]:
import numpy as np
import torch

การสร้างเเบบที่ใช้ array ของ Python ในการสร้าง

In [ ]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
print(x_data)

tensor([[1, 2],
        [3, 4]])


การสร้างเเบบที่สามารถใช้ Numpy array เป็นต้นเเบบเพื่อที่จะสร้าง tensor ที่มีค่าเเบบเดียวกันได้

In [ ]:
import numpy as np
data = [[5, 6], [7, 8]]
np_array = np.array(data)
print("Numpy array :\n", np_array)
import torch
x_np = torch.from_numpy(np_array)
print("Torch tensor :\n", x_np)

Numpy array :
 [[5 6]
 [7 8]]
Torch tensor :
 tensor([[5, 6],
        [7, 8]])


การสร้าง tensor เเบบที่กำหนดรูปร่าง (shape) ให้คล้ายกับ tensor ตัวอย่าง x_data

In [ ]:
x_ones = torch.ones_like(x_data) # retains the shape of x_data and fill all the value with 1
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # retains the shape of x_data and fill all the value with random float number in range of 0 to 1
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.7925, 0.6744],
        [0.2238, 0.1440]]) 



การสร้าง tensor เเบบที่กำหนดรูปร่าง (shape) ได้

In [ ]:
shape = (2, 3,) # (ROW, COLUMN, DEPTH, ...)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.8619, 0.2578, 0.6023],
        [0.1279, 0.7547, 0.7277]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


หรือสามารถส่งผ่าน shape ที่ต้องการผ่าน args โดยตรง

In [ ]:
tensor = torch.rand(3, 4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


# ข้อเเตกต่างระหว่าง Torch tensor กับ Numpy array

Torch tensor มีข้อเเตกต่างจาก Numpy array ตรงที่ Numpy array นั้นเวลาที่จะประมวลผลจำเป็นต้องใช้ CPU เท่านั้นในขณะที่ Torch tensor สามารถประมวลผลผ่าน GPU ด้วย CUDA เพื่อที่จะเร่งความเร็วในการประมวลผลได้

In [ ]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
  tensor = tensor.to('cuda')
  print(f"Device tensor is stored on: {tensor.device}")

การคูณ $2^2$ ใน Numpy array

In [ ]:
A = np.array([[1,2], [3,4], [5,6], [7,8], [9,10]])
for i in range(2):
  A *= 2
print(A)

[[ 4  8]
 [12 16]
 [20 24]
 [28 32]
 [36 40]]


In [ ]:
T = torch.tensor([[1,2], [3,4], [5,6], [7,8], [9,10]])
T.mul(2**2)

tensor([[ 4,  8],
        [12, 16],
        [20, 24],
        [28, 32],
        [36, 40]])

# การเเก้ไข tensor

นอกจากนั้นเเล้ว tensor ยังเสนอวิธีต่างๆในการเเก้ไขที่ง่ายต่อการใช้งานอีกด้วย

In [ ]:
print(tensor, "\n")
tensor.add_(5) # add 5 to the entire tensor
print(tensor)

tensor([[0.4391, 0.6524, 0.8845, 0.4004],
        [0.7932, 0.3166, 0.3491, 0.6001],
        [0.4743, 0.8598, 0.3384, 0.7108]]) 

tensor([[5.4391, 5.6524, 5.8845, 5.4004],
        [5.7932, 5.3166, 5.3491, 5.6001],
        [5.4743, 5.8598, 5.3384, 5.7108]])


In [ ]:
tensor = torch.ones(4, 4)
tensor[2,3] = 0 # set value for specific point in tensor
print(tensor)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 0.],
        [1., 1., 1., 1.]])


In [ ]:
tensor = torch.ones(4, 4)
tensor[2,3] = 0
t1 = torch.cat([tensor, tensor, tensor], dim=0)
print("Row concat : \n",t1)
t2 = torch.cat([tensor, tensor, tensor], dim=1)
print("Column concat : \n", t2)

Row concat : 
 tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 0.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 0.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 0.],
        [1., 1., 1., 1.]])
Column concat : 
 tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])


การคำนวณเชิง Matrix

In [ ]:
# tensor1 = torch.rand(4,4)
# tensor2 = torch.rand(4,4)

tensor1 = torch.tensor([[1,2],[3,4]])
tensor2 = torch.tensor([[5,6],[7,8]])
print("T1: \n", tensor1, "\nT2: \n", tensor2)
# This computes the element-wise product
print(f"tensor.mul(tensor) \n {tensor1.mul(tensor2)} \n")
# Alternative syntax:
print(f"tensor * tensor \n {tensor1 * tensor2}")

T1: 
 tensor([[1, 2],
        [3, 4]]) 
T2: 
 tensor([[5, 6],
        [7, 8]])
tensor.mul(tensor) 
 tensor([[ 5, 12],
        [21, 32]]) 

tensor * tensor 
 tensor([[ 5, 12],
        [21, 32]])


In [ ]:
tensor = torch.ones(4, 4)
tensor[1,] = 0
print(f"tensor.matmul(tensor) \n {tensor.matmul(tensor)} \n")
# Alternative syntax:
print(f"tensor @ tensor \n {tensor @ tensor}")

tensor.matmul(tensor) 
 tensor([[3., 3., 3., 3.],
        [0., 0., 0., 0.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 

tensor @ tensor 
 tensor([[3., 3., 3., 3.],
        [0., 0., 0., 0.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


In [ ]:
print(f"tensor.matmul(tensor.T) \n {tensor.matmul(tensor.t())} \n")
# Alternative syntax:
print(f"tensor @ tensor.T \n {tensor @ tensor.t()}")

tensor.matmul(tensor.T) 
 tensor([[4., 0., 4., 4.],
        [0., 0., 0., 0.],
        [4., 0., 4., 4.],
        [4., 0., 4., 4.]]) 

tensor @ tensor.T 
 tensor([[4., 0., 4., 4.],
        [0., 0., 0., 0.],
        [4., 0., 4., 4.],
        [4., 0., 4., 4.]])


# HW1_2
1. จงเขียนโค้ดเพื่อให้ได้ผลลัพธ์ดังภาพ

```
tensor([[1., 2., 3., 4.],
        [2., 3., 4., 5.],
        [3., 4., 5., 6.],
        [4., 5., 6., 7.]])
```
โดยเริ่มต้นจาก
 tensor = torch.ones(4, 4)



In [ ]:
tensor = torch.ones(4, 4)
tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
increment_tensor = torch.arange(4)
for Idx in range(tensor.size(0)):
  tensor[Idx] = tensor[Idx] + (increment_tensor + 1*Idx)

tensor

tensor([[1., 2., 3., 4.],
        [2., 3., 4., 5.],
        [3., 4., 5., 6.],
        [4., 5., 6., 7.]])