# Numpy Tutorial
Ref: https://www.w3schools.com/python/numpy/default.asp

##### Sample

numpy array นั้นมี requirements ที่มากกว่าของ array ปกติ เนื่องจากหากกำหนดให้ข้อมูลภายในนั้นเป็นชนิดใดก็ตามแล้ว ภายใน array นั้น ๆ จะต้องมีข้อมูลชนิดนั้นเท่านั้น เช่น ต้องเป็นตัวอักษรทั้งหมด หรือต้องเป็นตัวเลขทั้งหมด แต่ความยุ่งยากนี้แลกมากับความเร็วในการทำงานที่มากขึ้น ดังตัวอย่างด้านล่าง

In [1]:
import numpy as np
import time

size = 100_000

list1 = np.random.randint(0, 10, size).tolist()
list2 = np.random.randint(0, 10, size).tolist()

array1 = np.array(list1)
array2 = np.array(list2)

start_time = time.time()
result_list = [list1[i] + list2[i] for i in range(size)]
list_time = time.time() - start_time
start_time = time.time()
result_array = array1 + array2
numpy_time = time.time() - start_time

results_equal = result_list == result_array.tolist()

print("Python list time:", list_time, "seconds")
print("Python result:", result_list)
print("NumPy array time:", numpy_time, "seconds")
print("NumPy result:", result_array)
print("is equal :", results_equal)

Python list time: 0.006580829620361328 seconds
Python result: [4, 5, 13, 14, 4, 15, 10, 4, 8, 12, 13, 11, 8, 11, 7, 15, 8, 11, 6, 9, 10, 13, 11, 6, 5, 8, 3, 3, 9, 6, 9, 6, 6, 7, 15, 13, 5, 14, 18, 14, 6, 9, 5, 5, 10, 7, 7, 11, 16, 10, 7, 5, 10, 15, 5, 3, 9, 7, 8, 5, 7, 17, 3, 10, 5, 8, 7, 10, 2, 2, 9, 12, 3, 0, 5, 6, 9, 2, 10, 18, 15, 10, 7, 10, 13, 13, 9, 5, 6, 16, 9, 11, 17, 16, 10, 14, 11, 3, 10, 17, 5, 8, 10, 4, 11, 14, 13, 13, 9, 14, 6, 13, 15, 10, 12, 8, 9, 15, 10, 4, 9, 9, 11, 13, 15, 9, 11, 1, 8, 11, 9, 13, 13, 3, 16, 0, 9, 11, 10, 13, 1, 13, 3, 10, 16, 9, 17, 6, 15, 4, 12, 10, 8, 16, 12, 4, 16, 6, 18, 7, 1, 9, 8, 4, 8, 15, 11, 9, 15, 8, 12, 7, 11, 13, 8, 17, 6, 9, 12, 10, 14, 11, 7, 6, 7, 17, 13, 13, 8, 11, 8, 9, 7, 12, 4, 13, 13, 7, 4, 2, 4, 14, 14, 9, 9, 12, 14, 7, 11, 6, 16, 10, 17, 10, 9, 8, 5, 11, 11, 5, 17, 11, 6, 4, 6, 2, 12, 7, 6, 5, 16, 14, 6, 6, 12, 8, 5, 10, 5, 12, 7, 9, 9, 12, 6, 5, 14, 16, 8, 14, 3, 1, 6, 4, 16, 12, 12, 6, 10, 9, 5, 9, 12, 7, 12, 7, 2, 4, 13, 10, 

In [2]:
arr = [1, 2, 3, 4, 5]

In [3]:
arr = np.array(arr)
arr

array([1, 2, 3, 4, 5])

In [4]:
print(np.__version__)

2.1.3


##### Creating arrays

In [5]:
# 0-D == scalar value (Only value, none of matrix)
arr = np.array(42)
print(arr, arr.shape)

42 ()


In [6]:
# 1-D = Only H or W vector array (Only Height or Width)
arr = np.array([3, 2])
print(arr, arr.shape)

[3 2] (2,)


In [7]:
# 2-D == H x W matrix array (Height x Width))
arr = np.array([[1, 0, 1], [3, 4, 1]])
print(arr, arr.shape)

[[1 0 1]
 [3 4 1]] (2, 3)


In [8]:
# 3-D == D x H x W matrix array (Deep x Height x Width)
arr = np.array([[[1, 7, 9], [5, 9, 3], [7, 9, 9]], [[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
print(arr, arr.shape)

[[[1 7 9]
  [5 9 3]
  [7 9 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]] (2, 3, 3)


![Sample_arrays.png](attachment:Sample_arrays.png)

Array Elements and Indexing

In [9]:
# 1-D (4 width)
arr = np.array([1, 2, 3, 4])
print(arr[0])
print(arr[1])
print(arr[2] + arr[3])

1
2
7


In [10]:
# 2-D (5 width x 2 height)
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('2nd element on 1st row: ', arr[0, 1])
print('5th element on 2nd row: ', arr[1, 4])
print('Optional: 5th element on 2nd row: ', arr[1, -1])
print('Sum of 1st element on 1st row and 4th element on 2nd row: ', arr[0, 0]+arr[1, 3])

2nd element on 1st row:  2
5th element on 2nd row:  10
Optional: 5th element on 2nd row:  10
Sum of 1st element on 1st row and 4th element on 2nd row:  10


In [11]:
# 3-D (2 depth x 3 width x 2 height)
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print('Last element from 1st matrix: ', arr[0, 1, 2])
print('First element from 1st matrix: ', arr[1, 0, 0])
print('Last row from 2nd matrix: ', arr[1, -1])
print('First row from 1st matrix: ', arr[0, 0])
print('1st matrix: ', arr[0])
print('2nd matrix: ', arr[1])

Last element from 1st matrix:  6
First element from 1st matrix:  7
Last row from 2nd matrix:  [10 11 12]
First row from 1st matrix:  [1 2 3]
1st matrix:  [[1 2 3]
 [4 5 6]]
2nd matrix:  [[ 7  8  9]
 [10 11 12]]


##### Array Slicing

In [12]:
# 1-D
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print("Indexing order")
print(arr[1:5])
print(arr[5:7])
print(arr[3: ])
print(arr[ :4])

Indexing order
[2 3 4 5]
[6 7]
[4 5 6 7]
[1 2 3 4]


In [13]:
print("Indexing reversed order (minus operation)")
print(arr[2:-1])
print(arr[-3:-1])

Indexing reversed order (minus operation)
[3 4 5 6]
[5 6]


In [14]:
print("Indexing skip order")
print(arr[::1])
print(arr[::2])
print("Indexing skip order/normal operation")
print(arr[3::1])
print(arr[1:5:2])
print("Indexing skip order/minus-reversed operation")
print(arr[:-1:2])
print(arr[-4:-1:2])

Indexing skip order
[1 2 3 4 5 6 7]
[1 3 5 7]
Indexing skip order/normal operation
[4 5 6 7]
[2 4]
Indexing skip order/minus-reversed operation
[1 3 5]
[4 6]


In [15]:
# 2-D
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print("Indexing order")
print(arr[1, 1:4])
print(arr[0:2, 2])
print(arr[0:2, 1:4])

Indexing order
[7 8 9]
[3 8]
[[2 3 4]
 [7 8 9]]


##### Data Types

i - integer\
b - boolean\
u - unsigned integer\
f - float\
c - complex float\
m - timedelta\
M - datetime\
O - object\
S - string\
U - unicode string\
V - fixed chunk of memory for other type ( void )

In [16]:
# integer
arr = np.array([1, 2, 3, 4])
print(arr.dtype)

int64


In [17]:
# float
arr = np.array([1., 2.5, 3.0, 4.2345697789])
print(arr.dtype)

float64


In [18]:
# strings
arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype)

<U6


In [19]:
# string
arr = np.array([1, 2, 3, 4], dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [20]:
# 4 bytes integer
arr = np.array([1, 2, 3, 4], dtype='i4')
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [49]:
# conversion
# 1st: float-to-int
arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype('i')
print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [22]:
# 2nd: float-to-int
arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype(int)
print(newarr)
print(newarr.dtype)

[1 2 3]
int64


In [23]:
# int-to-bool
arr = np.array([1, 0, 3])
newarr = arr.astype(bool)
print(newarr)
print(newarr.dtype)

[ True False  True]
bool


##### Array Copying

In [24]:
# copy
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42
print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


.view() ใช้บ่อย จำไว้ให้ดี

In [25]:
# change the original array, make a view (if arr changed, x got changed, like a mirroring)
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42
print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [26]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31
print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


##### Shape and reshape

In [27]:
# Shape
arr = np.array([1, 2, 3, 4])
print(arr)
print('pre-shape of array with added dimension:', arr.shape)
print('\n'*3)
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('pre-shape of array with added dimension:', arr.shape)

[1 2 3 4]
pre-shape of array with added dimension: (4,)




[[[[[1 2 3 4]]]]]
pre-shape of array with added dimension: (1, 1, 1, 1, 4)


In [28]:
# Reshape 1-D to 2-D

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print(arr, arr.shape)
newarr = arr.reshape(4, 3)
print(newarr, newarr.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12] (12,)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] (4, 3)


In [29]:
# Reshape 1-D to 3-D

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2)
print(newarr, newarr.shape)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)


In [30]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarr = arr.reshape(2, 2, -1)
print(newarr, newarr.shape)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]] (2, 2, 2)


##### Iterating Arrays

Iterating 2-D Arrays

In [31]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)
# print sub-vector (1D) of 2-D array
for x in arr:
  print(x)

(2, 3)
[1 2 3]
[4 5 6]


In [32]:
# print sub-element (scalar) of sub-array of 2-D array
for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


Iterating 3-D Arrays

In [33]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr.shape)

# print sub-matrix (2D) of 3-D array
for x in arr:
  print(x)

(2, 2, 3)
[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [34]:
# print sub-vector (1D) of subsub-matrix (2D) of 3-D array
for x in arr:
  for y in x:
    print(y)

[1 2 3]
[4 5 6]
[7 8 9]
[10 11 12]


In [35]:
# print sub-element (scalar) of sub-vector (1D) of subsub-matrix (2D) of 3-D array
for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [36]:
#Optional: print sub-element via np.nditer
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [37]:
arr = np.array([1, 2, 3])
for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')


In [38]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
for x in np.nditer(arr[:,::2]):
  print(x)

1
3
5
7


In [39]:
arr = np.array([1, 2, 3])
for idx, x in np.ndenumerate(arr):
  print(idx, x)

print('-'*10)
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3
----------
(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


##### Array Concatenation & Stacking

In [56]:
# 1-D concat
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print(arr, arr.shape)

[1 2 3 4 5 6] (6,)


In [53]:
# 2-D concat
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2), axis=1)
print(arr, arr.shape)

[[1 2 5 6]
 [3 4 7 8]] (2, 4)


In [42]:
# 1-D hstack (horizontal stack)
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.hstack((arr1, arr2))
print(arr, arr.shape)

[1 2 3 4 5 6] (6,)


In [43]:
# 1-D vstack (vertical stack)
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.vstack((arr1, arr2))
print(arr, arr.shape)

[[1 2 3]
 [4 5 6]] (2, 3)


In [44]:
# 1-D dstack (depth stack)
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.dstack((arr1, arr2))
print(arr, arr.shape)

[[[1 4]
  [2 5]
  [3 6]]] (1, 3, 2)


##### Array Spliting

In [45]:
# 1-D
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
print(newarr, newarr[0].shape)

[array([1, 2]), array([3, 4]), array([5, 6])] (2,)


In [46]:
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 4)
print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [47]:
# 2-D

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
newarr = np.array_split(arr, 3)
print(newarr, newarr[0].shape)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])] (2, 2)


In [48]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.array_split(arr, 3)
print(newarr, newarr[0].shape)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])] (2, 3)


# HW1_1

1. ``` np.array([[[1, 1, 1], [1, 1, 1]], [[1, 1, 1], [1, 1, 1]]])``` จงหาขนาด Dimension ของมิติที่ข้างต้น

2. ```arr = np.array([[[1, 2], [2, 1]], [[3, 2], [2, 3]], [[4, 3], [3, 4]]])``` จงหา \
  2.1 arr[0, 0, 0] + arr[1, 1, 1] + arr[2, 2, 2] \
  2.2 arr[0] + arr[1]