In [244]:
import numpy as np
import time

In [245]:
arr= np.array([1,2,3,4])
new_arr = arr.reshape(2, 2)
new_arr

array([[1, 2],
       [3, 4]])

In [246]:
new_arr_1 =  np.array(
    [0,1,0,4]
).reshape(2,2)
new_arr_1 = np.multiply(new_arr_1, -5)
new_arr_1

array([[  0,  -5],
       [  0, -20]])

In [247]:
arr_rand = np.array(np.random.randint(0, 10, 4).tolist()).reshape(2,2)
arr_rand

array([[5, 2],
       [8, 6]])

In [248]:
arr = np.subtract(new_arr_1, arr_rand)
arr

array([[ -5,  -7],
       [ -8, -26]])

In [249]:
arr = arr[0, :]
arr

array([-5, -7])

In [250]:
arr = np.concatenate((arr, arr)).reshape(1 , -1)
arr

array([[-5, -7, -5, -7]])

In [251]:
arr_T = arr.T
arr_T

array([[-5],
       [-7],
       [-5],
       [-7]])

In [252]:
res_arr = arr_T.dot(arr)
res_arr

array([[25, 35, 25, 35],
       [35, 49, 35, 49],
       [25, 35, 25, 35],
       [35, 49, 35, 49]])

In [253]:
res_arr.max()

np.int64(49)